[package]
disabled = true

[python]
python_binary = ["py"]
detect_folders = [".venv"]
format = '[(\($virtualenv\) )]($style)'

[directory]
style = "blue"
truncation_length = 3
truncation_symbol = "…/"

[username]
style_user = "green"
format = "[$user]($style)@"
disabled = false
show_always = true

[hostname]
ssh_only = false
format = "[$hostname]($style):"
disabled = false

[nodejs]
disabled = true
